const carsData = [
  {
    id: 1,
    name: "Koegnisegg",
    type: "Sport",
    price: "99",
    fuel: "90",
    transmission: "Manual",
    capacity: "2",
    image: "/common/cars/koegin.svg",
  },
  {
    id: 2,
    name: "Nissan GT-R",
    type: "Sport",
    price: "100",
    fuel: "80",
    transmission: "Manual",
    capacity: "2",
    discount: "20",
    image: "/common/cars/nissan.svg",
  },
  {
    id: 3,
    name: "Rolls-Royce",
    type: "Sport",
    price: "96",
    fuel: "70",
    transmission: "Manual",
    capacity: "4",
    image: "/common/cars/rollsroyce.svg",
  },
  {
    id: 4,
    name: "Nissan GT-R",
    type: "Sport",
    price: "100",
    fuel: "80",
    transmission: "Manual",
    capacity: "2",
    discount: "20",
    image: "/common/cars/nissan.svg",
  },
  {
    id: 5,
    name: "MGZX Exclusive",
    type: "Hatcback",
    price: "76",
    fuel: "70",
    transmission: "Manual",
    capacity: "4",
    image: "/common/cars/mgzx.svg",
  },
  {
    id: 6,
    name: "All New Terios",
    type: "SUV",
    price: "74",
    fuel: "90",
    transmission: "Manual",
    capacity: "6",
    image: "/common/cars/terios.svg",
  },
  {
    id: 7,
    name: "New MGZS",
    type: "SUV",
    price: "80",
    fuel: "80",
    transmission: "Manual",
    capacity: "6",
    image: "/common/cars/newmgzs.svg",
  },
  {
    id: 8,
    name: "Koegnisegg",
    type: "Sport",
    price: "99",
    fuel: "90",
    transmission: "Manual",
    capacity: "2",
    image: "/common/cars/koegin.svg",
  },
  {
    id: 9,
    name: "Nissan GT-R",
    type: "Sport",
    price: "100",
    fuel: "80",
    transmission: "Manual",
    capacity: "2",
    discount: "20",
    image: "/common/cars/nissan.svg",
  },
  {
    id: 10,
    name: "Rolls-Royce",
    type: "Sport",
    price: "96",
    fuel: "70",
    transmission: "Manual",
    capacity: "4",
    image: "/common/cars/rollsroyce.svg",
  },
  {
    id: 11,
    name: "Nissan GT-R",
    type: "Sport",
    price: "80",
    fuel: "80",
    transmission: "Manual",
    capacity: "2",
    discount: "50",
    image: "/common/cars/nissan.svg",
  },
  {
    id: 12,
    name: "MGZX Exclusive",
    type: "Hatcback",
    price: "80",
    fuel: "70",
    transmission: "Manual",
    capacity: "4 ",
    discount: "4",
    image: "/common/cars/mgzx.svg",
  },
];
export default carsData;
