const carsData = [
    {
        id: 1,
        carName: "All New Rush",
        carsType: "SUV",
        carImage: "/recommendationCar/allNewRush-gray.png",
        gas: 70,
        gear: "Manual",
        user: 6,
        price: 80,
        discount: 5,
    },
    {
        id: 2,
        carName: "CR - V",
        carsType: "SUV",
        carImage: "/recommendationCar/cr-v-brown.png",
        gas: 80,
        gear: "Manual",
        user: 6,
        price: 80,
        discount: 0,
    },
    {
        id: 3,
        carName: "All New Terios",
        carsType: "SUV",
        carImage: "/recommendationCar/allNewTerios-blue.png",
        gas: 90,
        gear: "Manual",
        user: 6,
        price: 74,
        discount: 0,
    },
    {
        id: 4,
        carName: "Koenigsegg",
        carsType: "Sport",
        carImage: "/recommendationCar/koenigsegg-white.png",
        gas: 90,
        gear: "Manual",
        user: 2,
        price: 99,
        discount: 0,
    },
    {
        id: 5,
        carName: "Nissan GT - R",
        carsType: "Sport",
        carImage: "/recommendationCar/nissanGT-R-gray.png",
        gas: 80,
        gear: "Manual",
        user: 2,
        price: 100,
        discount: 20,
    },
    {
        id: 6,
        carName: "Rolls-Royce",
        carsType: "Sport",
        carImage: "/recommendationCar/rolls-Royce-blue.png",
        gas: 70,
        gear: "Manual",
        user: 4,
        price: 96,
        discount: 0,
    },
    {
        id: 7,
        carName: "CR  - V",
        carsType: "SUV",
        carImage: "/recommendationCar/cr-v-black.png",
        gas: 80,
        gear: "Manual",
        user: 6,
        price: 80,
        discount: 0,
    },
    {
        id: 8,
        carName: "MG ZX Exclusice",
        carsType: "Hatchback",
        carImage: "/recommendationCar/mGZXExclusice-blue.png",
        gas: 70,
        gear: "Manual",
        user: 4,
        price: 80,
        discount: 4,
    },
    {
        id: 9,
        carName: "New MG ZS",
        carsType: "SUV",
        carImage: "/recommendationCar/newMG-ZS-gray.png",
        gas: 80,
        gear: "Manual",
        user: 6,
        price: 80,
        discount: 0,
    },
    {
        id: 10,
        carName: "New MG ZS",
        carsType: "SUV",
        carImage: "/recommendationCar/newMG-ZS-white.png",
        gas: 80,
        gear: "Manual",
        user: 6,
        price: 95,
        discount: 15,
    },
    {
        id: 11,
        carName: "Rolls-Royce",
        carsType: "Sport",
        carImage: "/recommendationCar/rolls-Royce-blue.png",
        gas: 70,
        gear: "Manual",
        user: 4,
        price: 96,
        discount: 0,
    },
    {
        id: 12,
        carName: "CR - V",
        carsType: "SUV",
        carImage: "/recommendationCar/cr-v-brown.png",
        gas: 80,
        gear: "Manual",
        user: 6,
        price: 80,
        discount: 0,
    },
];

export default carsData;
